### ISSUE TITLE
Recommendation for viewing the data

### ISSUE THREAD

**Issue by networknerdz** [VerizonDigital/vflow#122]
Hi all, thanks for open sourcing this project, it looks neat.

I have things up and running and data being collected, but I am kinda stumped on a good way to visualize it (grafana?). Does anyone have any recommendations? I am new to Kafka, but have used Graphite/Grafana before. 

Any open source projects that would be easy to integrate with vflow? Or any ideas from the maintainers on how they visualize the data would be greatly appreciated.

Thanks!

**Comment by leoluk** [comment]
If you need something that works out of the box, https://github.com/robcowart/elastiflow (rather than vflow) would probably be your best bet.

vflow is more of a building piece for a custom data aggregation/processing pipeline. We use it with a custom ClickHouse importer and a bunch of services that run SQL queries for intrusion detection.

**Comment by networknerdz** [comment]
Thanks very much @leoluk! If you dont mind letting me leave the issue open for a couple of days to see if anyone else has other scenarios to share I would appreciate it. Either way tyvm!
