### ISSUE TITLE
Unified configuration and flags

### ISSUE THREAD

**Issue by jrossi** [VerizonDigital/vflow#17]
Currently vflow uses a few different files for configuration, and some of it's not super easy to keep track of.  Nor allow some features to be excluded (mirror on windows #16 ) 

Would this project be willing to accept something a little more complete and unified?  Some examples of ideas:
* https://github.com/jessevdk/go-flags
* https://github.com/spf13/viper + https://github.com/spf13/cobra

I happen to like the go-flags library as it's easy and works with files, flags, and environment variables.

**Comment by mehrdadrad** [comment]
@jrossi in this project tries to use less 3rd party packages as much as possible. the mentioned packages are awesome but not necessary to use them. thanks for your suggestions.

**Comment by jrossi** [comment]
Understood, and maybe third party depends are not the correct way.  What about a more unified configuration system that was a single config file for everything?

**Comment by mehrdadrad** [comment]
there are only two configs: 1- main config  2- producer config 
the producers are kind of plugin, separate of the vFlow core. they just register at vFlow.
The producers can have their specific parameters in their own config and works independent  without any change at vFlow core. any benefit of having a config instead of two?
