### ISSUE TITLE
IPFIX: Interpret Type Conversions Unsafe?

### ISSUE THREAD

**Issue by tim-hutchinson** [VerizonDigital/vflow#41]
While debugging an interpret error related to #30, I noticed that the `Interpret` [function](https://github.com/VerizonDigital/vflow/blob/master/ipfix/interpret.go#L67) returns have different behavior than I would have expected:

1) Why create another value after converting the byte array to `Uint64`? i.e. why not  `return binary.BigEndian.Uint64(*b)` I'm new to Go, so this may make complete sense and I'm just unaware
2) Won't converting from an `uint` to an `int` put you at risk of going out of range?

**Comment by mehrdadrad** [comment]
@tim-hutchinson the out of index comes from binary.BigEndian.Uint64. the root cause of this issue related to the DateTmeSeconds which it has 4 bytes but the interpret wants to convert to Uint64 through binary.BigEndian.Uint64. the DateTimeSeconds needs to interpret by binary.BigEndian.Uint32 instead. I'll commit this fix soon.
```
RFC7011
  The IPFIX Message Header Export Time field is the time at which the
   IPFIX Message Header leaves the Exporter, using the same encoding as
   the dateTimeSeconds abstract data type [RFC7012], i.e., expressed in
   seconds since the UNIX epoch, 1 January 1970 at 00:00 UTC, encoded as
   an unsigned 32-bit integer.
```
